export GOOGLE_AUTH_CLIENT_ID=[GOOGLE AUTH CLIENT ID]
export GOOGLE_AUTH_SECRET=[GOOGLE AUTH SECRET]
export GOOGLE_AUTH_CALLBACK_URL=http://localhost:8080/auth/google/callback
export APPSERVER_AUTH_SECRET=supersecret
export APPSERVER_AUTH_EXPIRED_IN=1day
export APPSERVER_PORT=8080
export UI_AUTH_URL=http://localhost:8080/#/auth